#!/usr/bin/env groovy

pipeline {
        agent any

        stages {
                stage('Checkout') {
                        steps {
                                git url: 'https://github.com/dmvo4935/terraform', 
                                        branch: 'master', 
                                        credentialsId: 'a797285f-cdb3-4556-acf8-e4fcc13dca54'
                        }
                }

                stage('Terraform') {
                        steps {
                                dir('terraform/' + buildPath) {
                                        /*
                                        sh 'terraform plan -destroy -var-file variable_values.tfvars'
                                        sh 'terraform destroy -var-file variable_values.tfvars --force'
                                        */

                                        sh '/opt/terraform/terraform init'
                                        sh '/opt/terraform/terraform plan -destroy'
                                        sh '/opt/terraform/terraform destroy --force'
                                }
                        }
                }
        }
}

