#!/usr/bin/env groovy

pipeline {
        agent any

        stages {
/*                stage('Checkout') {
                        steps {
                                git url: 'https://github.com/evry/cloudascore', 
                                        branch: 'master', 
                                        credentialsId: 'e74297bf-3674-4207-aecc-26ad65aa3f01'
                        }
                }
*/                
                stage('Terraform') {
                        steps {
                                dir('terraform/' + buildPath) {
                                        /*
                                        sh '/opt/terraform/terraform init -var-file variable_values.tfvars'
                                        sh '/opt/terraform/terraform plan -var-file variable_values.tfvars'
                                        sh '/opt/terraform/terraform apply -var-file variable_values.tfvars -auto-approve=true'
                                        */

                                        sh '/opt/terraform/terraform init'
                                        sh '/opt/terraform/terraform plan'
                                        sh '/opt/terraform/terraform apply -auto-approve=true'
                                        sh '/opt/terraform/terraform state pull'
 /*                                       sh '/opt/terraform/terraform state pull > terraform-test.tfstate' */
                                }
                        }
                }       
        }
}

