#!/usr/bin/env groovy

pipeline {
        agent any

        stages {
                stage('Checkout') {
                        steps {
                                git url: 'https://github.com/dmvo4935/terraform', 
                                        branch: 'master', 
                                        credentialsId: 'a797285f-cdb3-4556-acf8-e4fcc13dca54'
                        }
                }
                
                stage('Terraform') {
                        steps {
                                dir('terraform/' + buildPath) {
                                        /*
                                        sh '/opt/terraform/terraform init -var-file variable_values.tfvars'
                                        sh '/opt/terraform/terraform plan -var-file variable_values.tfvars'
                                        sh '/opt/terraform/terraform apply -var-file variable_values.tfvars -auto-approve=true'
                                        */

                                        sh '/opt/terraform/terraform init'
                                        sh '/opt/terraform/terraform plan'
                                        sh '/opt/terraform/terraform apply -auto-approve=true'
                                        sh '/opt/terraform/terraform state pull'
 /*                                       sh '/opt/terraform/terraform state pull > terraform-test.tfstate' */
                                }
                        }
                }       
        }
}

